# Generated by Django 5.2.5 on 2025-09-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('cih_bank', 'CIH Bank'), ('attijariwafa', 'Attijariwafa Bank'), ('bmce', 'BMCE Bank'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
