# Generated by Django 5.2.5 on 2025-09-09 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Image')),
                ('image_type', models.CharField(choices=[('main', 'Main Image'), ('front', 'Front View'), ('back', 'Back View'), ('side', 'Side View'), ('top', 'Top View'), ('bottom', 'Bottom View'), ('detail', 'Detail View'), ('reference', 'Reference/Serial'), ('package', 'Package'), ('accessories', 'Accessories')], default='detail', max_length=20, verbose_name='Image Type')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt Text')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
