# Generated by Django 5.2.5 on 2025-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('cash_delivery', 'Cash on Delivery'), ('wafacash', 'WafaCash'), ('cashplus', 'CashPlus'), ('baridbanque', 'Barid Bank'), ('bank_transfer', 'Bank Transfer'), ('cih_bank', 'CIH Bank'), ('attijariwafa', 'Attijariwafa Bank'), ('bmce', 'BMCE Bank')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
